services:
  hr-assistant:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      cache_from:
        - qd_hr_assistant-hr-assistant
    container_name: hr-assistant
    restart: unless-stopped
    networks:
      - hr-network
    ports:
      - "8000:8000"
    volumes:
      - ./uploaded_folders:/app/uploaded_folders
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static:/app/static
      - /dev/shm:/dev/shm
      - ./.env:/app/.env
    environment:
      - GRPC_DNS_RESOLVER=native
      - GRPC_ENABLE_FORK_SUPPORT=1
      - WORKERS=${WORKERS:-8}  # Increased default workers based on available CPU
      - TIMEOUT=300
      - KEEP_ALIVE=10
      - PORT=8000
      - LOG_LEVEL=info
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=random
      - UVICORN_WORKERS=8  # Explicitly set Uvicorn workers
      - UVICORN_WORKER_CLASS=uvicorn.workers.UvicornWorker
      - UVICORN_KEEPALIVE=10
      - UVICORN_TIMEOUT=300
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '8.0'  # Increased CPU limit
          memory: 12G   # Increased memory limit
        reservations:
          cpus: '2.0'
          memory: 4G
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_max_syn_backlog=65535
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
      - net.ipv4.tcp_fin_timeout=15
    ulimits:
      nofile:
        soft: 16384
        hard: 32768
    shm_size: '512mb'
    command: >
      gunicorn -c gunicorn.conf.py main:app

networks:
  hr-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  data:
    driver: local
  logs:
    driver: local
